### ISSUE TITLE
merge namespaced resources in config/routes.rb

### ISSUE THREAD

**Issue by Rabsztok** [d4rky-pl/admin-panel#1]
Upon creating second resource, it should be appended to existing admin namespace if possible.

For now, we get:

```
namespace :admin do
  resources :messages
end

namespace :admin do
  resources :posts
end
```

**Comment by d4rky-pl** [comment]
I was trying to use the built-in methods of doing scaffolding where possible so I'm afraid that's how Rails does it by default. I've checked that doing `rails generate scaffold admin::post` does exactly the same thing with either horrible regexes or hardcore code analysis (both ways are quite error-prone, I'm afraid).

Please reconsider if this problem is worth hacking this around.

**Comment by Rabsztok** [comment]
That's not an important feature, so we can leave it for later versions.

**Comment by d4rky-pl** [comment]
Does _we_ in your sentence imply I'm going to get this job? Because you know, you still didn't tell me and it's 5:22 PM ;)
