### ISSUE TITLE
Generating specs

### ISSUE THREAD

**Issue by Rabsztok** [d4rky-pl/admin-panel#2]
There should be an option to generate Rspec tests with FactoryGirl factories instead of standard fixtures. And use [pending method](https://www.relishapp.com/rspec/rspec-core/v/2-0/docs/pending/pending-examples) where we have no tests to add (models for example).

**Comment by d4rky-pl** [comment]
For everything other than controller test it's just a matter of configuring your application properly. Add `gem rspec-rails` and `gem factory_girl_rails` to your Gemfile and modify your `config/application.rb` to have the following lines:

``` ruby
config.generators do |g|
  g.test_framework :rspec
end
```

As for the controller test - I'm working on it but it'll require rewriting the current scaffolder to invoke the Rails' controller generator (and replacing view files with our own) instead of relying on custom code.
